#!/usr/bin/env bash
# scripts/validate.sh — Phase 2 deterministic validation. Default: typecheck + grep. Escalation: --probe-page. See references/validate.md.

set -euo pipefail

usage() { echo "Usage: validate.sh <ds-package-name> <surfaced-apis-file> [--probe-page]" >&2; exit 2; }
[[ "${1:-}" == "-h" || "${1:-}" == "--help" ]] && { usage; } || true

PROBE_PAGE=false; ARGS=()
for a in "$@"; do
  case "$a" in --probe-page) PROBE_PAGE=true ;; *) ARGS+=("$a") ;; esac
done
[[ ${#ARGS[@]} -lt 2 ]] && usage
PKG="${ARGS[0]}"; APIS_FILE="${ARGS[1]}"
[[ -f "$APIS_FILE" ]] || { echo "ERROR: surfaced-apis-file not found: $APIS_FILE" >&2; exit 2; }

SCRATCH=".extract-ds-skill-scratch"
mkdir -p "$SCRATCH"
[[ -f "$SCRATCH/.gitignore" ]] || echo "*" > "$SCRATCH/.gitignore"

APIS=()
while IFS= read -r line; do
  APIS+=("$line")
done < <(grep -vE '^\s*(#|$)' "$APIS_FILE" || true)
API_COUNT=${#APIS[@]}
[[ $API_COUNT -eq 0 ]] && { echo "ERROR: no APIs listed in $APIS_FILE" >&2; exit 2; }

# Unique top-level names (everything before the first dot).
TOPS=()
SEEN_TOPS=" "
for api in "${APIS[@]}"; do
  top="${api%%.*}"
  case "$SEEN_TOPS" in
    *" $top "*) ;;
    *) SEEN_TOPS="$SEEN_TOPS$top "; TOPS+=("$top") ;;
  esac
done

# ---------- Phase A: typecheck probe ----------
PROBE="$SCRATCH/probe.tsx"
{
  echo "// Auto-generated by extract-ds-skill/scripts/validate.sh. Do not edit."
  echo "import { $(IFS=,; echo "${TOPS[*]}") } from '$PKG';"
  echo "export const __probe = { $(IFS=,; echo "${TOPS[*]}") };"
  for api in "${APIS[@]}"; do echo "export const __ref_${api//./_} = $api;"; done
} > "$PROBE"

TSCONFIG="$SCRATCH/tsconfig.json"
PROJECT_TSCONFIG=""
for c in tsconfig.json tsconfig.base.json; do [[ -f "$c" ]] && { PROJECT_TSCONFIG="$c"; break; }; done
if [[ -n "$PROJECT_TSCONFIG" ]]; then
  cat > "$TSCONFIG" <<EOF
{ "extends": "../$PROJECT_TSCONFIG",
  "compilerOptions": { "noEmit": true, "jsx": "react-jsx", "skipLibCheck": true },
  "include": ["probe.tsx", "probe-page.tsx"] }
EOF
else
  cat > "$TSCONFIG" <<'EOF'
{ "compilerOptions": {
    "target": "ES2020", "module": "ESNext", "moduleResolution": "Bundler",
    "jsx": "react-jsx", "strict": true, "esModuleInterop": true,
    "skipLibCheck": true, "noEmit": true, "allowSyntheticDefaultImports": true },
  "include": ["probe.tsx", "probe-page.tsx"] }
EOF
fi

if command -v pnpm >/dev/null 2>&1; then TSC_CMD="pnpm tsc"
elif command -v npx >/dev/null 2>&1; then TSC_CMD="npx --no-install tsc"
else echo "ERROR: neither pnpm nor npx found" >&2; exit 2; fi

TSC_LOG="$SCRATCH/tsc.log"
set +e; $TSC_CMD --noEmit -p "$TSCONFIG" >"$TSC_LOG" 2>&1; TSC_EXIT=$?; set -e
TYPECHECK_OK=true
if [[ $TSC_EXIT -ne 0 ]]; then
  TYPECHECK_OK=false
  echo "TYPECHECK_FAIL"
  grep -E "probe\.tsx|error TS" "$TSC_LOG" || cat "$TSC_LOG"
fi

# ---------- Phase B: grep-resolves ----------
GREP_OK=true
PKG_JSON_PATH=""
command -v node >/dev/null 2>&1 && PKG_JSON_PATH=$(node -p "require.resolve('$PKG/package.json')" 2>/dev/null || true)
if [[ -z "$PKG_JSON_PATH" || ! -f "$PKG_JSON_PATH" ]]; then
  echo "GREP_MISS=__package_not_resolved__ ($PKG)"; GREP_OK=false
else
  PKG_DIR=$(dirname "$PKG_JSON_PATH")
  for top in "${TOPS[@]}"; do
    if ! grep -rEq "export.*\b${top}\b" "$PKG_DIR" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.mjs" --include="*.d.ts" 2>/dev/null; then
      echo "GREP_MISS=$top"; GREP_OK=false
    fi
  done
  $GREP_OK && echo "GREP_OK"
fi

# ---------- Optional: probe-page escalation ----------
if $PROBE_PAGE; then
  PP="$SCRATCH/probe-page.tsx"
  {
    echo "// Auto-generated probe page. Render in your own dev server (e.g. app/probe/page.tsx)."
    echo "import { $(IFS=,; echo "${TOPS[*]}") } from '$PKG';"
    echo "export default function ProbePage() {"
    echo "  return (<main style={{ padding: 24, display: 'grid', gap: 16 }}>"
    for top in "${TOPS[@]}"; do echo "    <section><h2>$top</h2><$top /></section>"; done
    echo "  </main>); }"
  } > "$PP"
  echo "PROBE_PAGE_WRITTEN=$PP"
fi

# ---------- Summary ----------
echo "VALIDATED_API_COUNT=$API_COUNT"
if $TYPECHECK_OK && $GREP_OK; then
  echo "VALIDATE_RESULT=PASS"; exit 0
else
  echo "VALIDATE_RESULT=FAIL"
  if ! $TYPECHECK_OK; then echo "FAIL_REASON=typecheck"; else echo "FAIL_REASON=grep"; fi
  exit 1
fi
