#!/usr/bin/env bash
# scripts/validate.sh — Phase 2 deterministic validation. Default: typecheck + grep,
# plus claims-file consumption (positive/negative prop claims → typed probe lines,
# PATH claims → test -e). Escalation: --probe-page. See references/validate.md.

set -euo pipefail

usage() { echo "Usage: validate.sh <ds-package-name> <surfaced-apis-file> [--claims <claims-file>] [--probe-page]" >&2; exit 2; }
[[ "${1:-}" == "-h" || "${1:-}" == "--help" ]] && { usage; } || true

PROBE_PAGE=false; CLAIMS_FILE=""; EXPECT_CLAIMS=false; ARGS=()
for a in "$@"; do
  if $EXPECT_CLAIMS; then CLAIMS_FILE="$a"; EXPECT_CLAIMS=false; continue; fi
  case "$a" in --probe-page) PROBE_PAGE=true ;; --claims) EXPECT_CLAIMS=true ;; *) ARGS+=("$a") ;; esac
done
if $EXPECT_CLAIMS; then echo "ERROR: --claims requires a file path" >&2; exit 2; fi
[[ ${#ARGS[@]} -lt 2 ]] && usage
PKG="${ARGS[0]}"; APIS_FILE="${ARGS[1]}"
[[ -f "$APIS_FILE" ]] || { echo "ERROR: surfaced-apis-file not found: $APIS_FILE" >&2; exit 2; }

SCRATCH=".extract-ds-skill-scratch"
mkdir -p "$SCRATCH"
[[ -f "$SCRATCH/.gitignore" ]] || echo "*" > "$SCRATCH/.gitignore"

# Claims-file auto-detect: extraction emits $SCRATCH/claims.txt (see
# references/validate.md, Claims file contract). --claims overrides.
if [[ -z "$CLAIMS_FILE" && -f "$SCRATCH/claims.txt" ]]; then CLAIMS_FILE="$SCRATCH/claims.txt"; fi

# ---------- Claims file parse ----------
# Grammar (one claim per line; # comments and blanks skipped):
#   Component.prop=value                  positive claim → typed assignment in the probe
#   NEGATIVE:Component.prop=value         negative claim → @ts-expect-error line in the probe
#   PATH:node_modules/<...>               cited local path → test -e (Phase C)
#   URL:<https-url>                       verified fetchable (HTTP 200) at extract time; NOT re-checked here
PROP_CLAIMS=()   # "P|N<TAB>Component<TAB>prop<TAB>value"
PATH_CLAIMS=()
N_POS=0; N_NEG=0; N_PATH=0; N_URL=0
if [[ -n "$CLAIMS_FILE" ]]; then
  [[ -f "$CLAIMS_FILE" ]] || { echo "ERROR: claims file not found: $CLAIMS_FILE" >&2; exit 2; }
  CLAIM_LINENO=0
  while IFS= read -r claim || [[ -n "$claim" ]]; do
    CLAIM_LINENO=$((CLAIM_LINENO + 1))
    if [[ "$claim" =~ ^[[:space:]]*(#|$) ]]; then continue; fi
    case "$claim" in
      URL:*) N_URL=$((N_URL + 1)) ;;
      PATH:node_modules/*) PATH_CLAIMS+=("${claim#PATH:}"); N_PATH=$((N_PATH + 1)) ;;
      PATH:*) echo "ERROR: $CLAIMS_FILE:$CLAIM_LINENO — PATH claims must be node_modules/-prefixed: $claim" >&2; exit 2 ;;
      NEGATIVE:[A-Za-z]*.*=*|[A-Za-z]*.*=*)
        kind="P"; body="$claim"
        [[ "$claim" == NEGATIVE:* ]] && { kind="N"; body="${claim#NEGATIVE:}"; }
        comp="${body%%.*}"; rest="${body#*.}"; prop="${rest%%=*}"; val="${rest#*=}"
        if [[ -z "$comp" || -z "$prop" || "$rest" == "$prop" ]]; then echo "ERROR: $CLAIMS_FILE:$CLAIM_LINENO — malformed claim: $claim" >&2; exit 2; fi
        PROP_CLAIMS+=("$kind	$comp	$prop	$val")
        if [[ "$kind" == "P" ]]; then N_POS=$((N_POS + 1)); else N_NEG=$((N_NEG + 1)); fi ;;
      *) echo "ERROR: $CLAIMS_FILE:$CLAIM_LINENO — unrecognized claim line: $claim" >&2; exit 2 ;;
    esac
  done < "$CLAIMS_FILE"
fi

APIS=()
while IFS= read -r __line; do APIS+=("$__line"); done < <(grep -vE '^\s*(#|$)' "$APIS_FILE" || true)
API_COUNT=${#APIS[@]}
[[ $API_COUNT -eq 0 ]] && { echo "ERROR: no APIs listed in $APIS_FILE" >&2; exit 2; }

# Unique top-level names (everything before the first dot).
# Portable (bash 3.2 compatible — macOS): colon-delimited "seen" string.
TOPS=()
SEEN=":"
for api in "${APIS[@]}"; do
  top="${api%%.*}"
  case "$SEEN" in
    *":$top:"*) ;;
    *) TOPS+=("$top"); SEEN="$SEEN$top:" ;;
  esac
done
# Claimed components must be importable too — a claim against a component the
# package does not export must fail the probe, not silently skip.
for spec in "${PROP_CLAIMS[@]+"${PROP_CLAIMS[@]}"}"; do
  if [[ -z "$spec" ]]; then continue; fi
  top="$(printf '%s' "$spec" | cut -f2)"
  case "$SEEN" in
    *":$top:"*) ;;
    *) TOPS+=("$top"); SEEN="$SEEN$top:" ;;
  esac
done

# ---------- Phase A: typecheck probe ----------
PROBE="$SCRATCH/probe.tsx"
{
  echo "// Auto-generated by extract-ds-skill/scripts/validate.sh. Do not edit."
  echo "import { $(IFS=,; echo "${TOPS[*]}") } from '$PKG';"
  if [[ ${#PROP_CLAIMS[@]} -gt 0 ]]; then echo "import type * as React from 'react';"; fi
  echo "export const __probe = { $(IFS=,; echo "${TOPS[*]}") };"
  for api in "${APIS[@]}"; do echo "export const __ref_${api//./_} = $api;"; done
  # Claims → typed assignments. Positive claims must typecheck; negative claims
  # carry @ts-expect-error so an upstream type widening is caught too (the
  # directive becomes unused → TS2578 fails the probe).
  CLAIM_I=0
  for spec in "${PROP_CLAIMS[@]+"${PROP_CLAIMS[@]}"}"; do
    if [[ -z "$spec" ]]; then continue; fi
    kind="$(printf '%s' "$spec" | cut -f1)"; comp="$(printf '%s' "$spec" | cut -f2)"
    prop="$(printf '%s' "$spec" | cut -f3)"; val="$(printf '%s' "$spec" | cut -f4)"
    case "$val" in
      true|false) tsval="$val" ;;
      ''|*[!0-9.]*) tsval="'$val'" ;;
      *) tsval="$val" ;;
    esac
    CLAIM_I=$((CLAIM_I + 1))
    if [[ "$kind" == "N" ]]; then echo "// @ts-expect-error NEGATIVE claim: $comp.$prop must reject $val"; fi
    echo "export const __claim_$CLAIM_I: React.ComponentProps<typeof $comp>['$prop'] = $tsval;"
  done
} > "$PROBE"

TSCONFIG="$SCRATCH/tsconfig.json"
PROJECT_TSCONFIG=""
for c in tsconfig.json tsconfig.base.json; do [[ -f "$c" ]] && { PROJECT_TSCONFIG="$c"; break; }; done
if [[ -n "$PROJECT_TSCONFIG" ]]; then
  cat > "$TSCONFIG" <<EOF
{ "extends": "../$PROJECT_TSCONFIG",
  "compilerOptions": { "noEmit": true, "jsx": "react-jsx", "skipLibCheck": true },
  "include": ["probe.tsx", "probe-page.tsx"] }
EOF
else
  cat > "$TSCONFIG" <<'EOF'
{ "compilerOptions": {
    "target": "ES2020", "module": "ESNext", "moduleResolution": "Bundler",
    "jsx": "react-jsx", "strict": true, "esModuleInterop": true,
    "skipLibCheck": true, "noEmit": true, "allowSyntheticDefaultImports": true },
  "include": ["probe.tsx", "probe-page.tsx"] }
EOF
fi

if command -v pnpm >/dev/null 2>&1; then TSC_CMD="pnpm tsc"
elif command -v npx >/dev/null 2>&1; then TSC_CMD="npx --no-install tsc"
else echo "ERROR: neither pnpm nor npx found" >&2; exit 2; fi

TSC_LOG="$SCRATCH/tsc.log"
set +e; $TSC_CMD --noEmit -p "$TSCONFIG" >"$TSC_LOG" 2>&1; TSC_EXIT=$?; set -e
TYPECHECK_OK=true
if [[ $TSC_EXIT -ne 0 ]]; then
  TYPECHECK_OK=false
  echo "TYPECHECK_FAIL"
  grep -E "probe\.tsx|error TS" "$TSC_LOG" || cat "$TSC_LOG"
fi

# ---------- Phase B: grep-resolves ----------
# Package-dir resolution is a fallback chain: (1) require.resolve('<pkg>/package.json')
# — throws ERR_PACKAGE_PATH_NOT_EXPORTED when a strict `exports` map omits the
# ./package.json subpath; (2) resolve the main entry and walk up to the nearest
# package.json whose `name` matches the package (skipping name-less type-marker
# files like dist/package.json); (3) node_modules/<pkg> on disk — covers
# ESM-only packages whose entry require.resolve cannot reach either.
GREP_OK=true
PKG_DIR=""
if command -v node >/dev/null 2>&1; then
  PKG_DIR=$(node -e '
    const path = require("path"), fs = require("fs");
    const pkg = process.argv[1];
    try { console.log(path.dirname(require.resolve(pkg + "/package.json"))); process.exit(0); } catch (e) {}
    try {
      let dir = path.dirname(require.resolve(pkg));
      while (dir !== path.dirname(dir)) {
        const pj = path.join(dir, "package.json");
        if (fs.existsSync(pj)) {
          try { if (JSON.parse(fs.readFileSync(pj, "utf8")).name === pkg) { console.log(dir); process.exit(0); } } catch (e) {}
        }
        dir = path.dirname(dir);
      }
    } catch (e) {}
    process.exit(1);
  ' "$PKG" 2>/dev/null || true)
fi
if [[ -z "$PKG_DIR" || ! -d "$PKG_DIR" ]]; then
  [[ -d "node_modules/$PKG" ]] && PKG_DIR="node_modules/$PKG" || PKG_DIR=""
fi
if [[ -z "$PKG_DIR" ]]; then
  echo "GREP_MISS=__package_not_resolved__ ($PKG)"; GREP_OK=false
else
  for top in "${TOPS[@]}"; do
    if ! grep -rEq "export.*\b${top}\b" "$PKG_DIR" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.mjs" --include="*.d.ts" 2>/dev/null; then
      echo "GREP_MISS=$top"; GREP_OK=false
    fi
  done
  $GREP_OK && echo "GREP_OK"
fi

# ---------- Phase C: cited-path claims ----------
# test -e runs only on node_modules/-prefixed paths (enforced at parse time).
# URL-shaped cites were verified fetchable at extract time and are not re-checked.
PATHS_OK=true
for p in "${PATH_CLAIMS[@]+"${PATH_CLAIMS[@]}"}"; do
  if [[ -z "$p" ]]; then continue; fi
  if [[ ! -e "$p" ]]; then echo "PATH_MISS=$p"; PATHS_OK=false; fi
done

# ---------- Optional: probe-page escalation ----------
if $PROBE_PAGE; then
  PP="$SCRATCH/probe-page.tsx"
  {
    echo "// Auto-generated probe page. Render in your own dev server (e.g. app/probe/page.tsx)."
    echo "import { $(IFS=,; echo "${TOPS[*]}") } from '$PKG';"
    echo "export default function ProbePage() {"
    echo "  return (<main style={{ padding: 24, display: 'grid', gap: 16 }}>"
    for top in "${TOPS[@]}"; do echo "    <section><h2>$top</h2><$top /></section>"; done
    echo "  </main>); }"
  } > "$PP"
  echo "PROBE_PAGE_WRITTEN=$PP"
fi

# ---------- Summary ----------
echo "VALIDATED_API_COUNT=$API_COUNT"
if [[ -n "$CLAIMS_FILE" ]]; then echo "CLAIMS_CHECKED=positive:$N_POS negative:$N_NEG path:$N_PATH url-skipped:$N_URL"; fi
if $TYPECHECK_OK && $GREP_OK && $PATHS_OK; then
  echo "VALIDATE_RESULT=PASS"; exit 0
else
  echo "VALIDATE_RESULT=FAIL"
  if ! $TYPECHECK_OK; then echo "FAIL_REASON=typecheck"
  elif ! $GREP_OK; then echo "FAIL_REASON=grep"
  else echo "FAIL_REASON=path"; fi
  exit 1
fi
